// Generated by CoffeeScript 1.10.0
(function() {
  window.initVideo = function(callback, width, height) {
    var canvas, handleVideo, spec, video;
    if (width == null) {
      width = 320;
    }
    if (height == null) {
      height = 240;
    }
    navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia || navigator.oGetUserMedia;
    video = document.createElement('video');
    video.width = width;
    video.height = height;
    canvas = document.createElement('canvas');
    handleVideo = function(stream) {
      video.src = URL.createObjectURL(stream);
      return video.addEventListener('canplay', function(e) {
        video.play();
        console.log(video.videoWidth, video.videoHeight);
        return callback({
          stream: stream,
          video: video,
          canvas: canvas
        });
      });
    };
    spec = {
      video: {
        mandatory: {
          minWidth: width,
          minHeight: height,
          maxWidth: width,
          maxHeight: height
        }
      }
    };
    return navigator.getUserMedia(spec, handleVideo, function(e) {
      return console.log(e);
    });
  };

}).call(this);
